server:
  port: 8081
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/phoneshop_rithy
    username: phoneshop_rithy
    password: 1234qwer
  jpa:
    hibernate:
      ddl-auto: update # Note: Often set to 'validate' or 'none' when using Liquibase
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    enabled: true
